### PR TITLE
new-form boat updated design

### PR DESCRIPTION
**Pull request by rsmml**
I change the Boats#New page, I gave it a bit style: [take a look here](https://recordit.co/oTGxr7DxYP)

- I still miss the Images but It will be under the price. Also I saw there's a way to preview the picture you are going to upload, so I'll try to implement that.

### CODE REVIEW

**Comment by rsmml** [comment]
**Not ready to merge yet** just after I do the pictures feature.

**Comment by chihoko12** [comment]
Very nice!

**Comment by sorina-duca** [comment]
Holy Moses, that looks really nice and realistic! Really nice job!

**Comment by rsmml** [comment]
**Ready to Merge**
I tried to make the preview for the picture but it's way to complicated.  I tried to make that the user can upload more than 1 picture. It works but it breaks on the boats index and show. I used the each method, to interact over the array of pictures but it doesn't work. So for now we have just 1 picture/boat

**Pull request merged**
