### PR TITLE
Add cancel to bookings controller

### PR DESCRIPTION
**Pull request by chihoko12**
add status change of cancel. 

when a user books a boat, the status is "pending". 
when the user cancels the booking, the status changes to "cancelled"

"approved" status is not taken into consideration yet. 

The booking price is calculated based on the assumption that the boat price is daily, not hourly rate. But this can be changed to hourly basis. 

Screenshot 2020-07-09 at 23 30 23
Screenshot 2020-07-09 at 23 31 17

### CODE REVIEW

**Comment by rsmml** [comment]
Oh cool I just saw it, after I comment the lines on the other request. Let's add tomorrow the Approved status 😄

**Comment by rsmml** [comment]
I realized that you made 2 branches and you worked on the same file. Be careful with that because I believe it can create some conflicts. If we merge the other pull request, then this one will have as origin another code and will create a conflict. In bots files the  @booking.price  line is different. 
So if we merge the first pull, then in master you will have a new line of code, different of the master when you started this branch. Did you got it? I can explain in better tomorrow.

**Comment by chihoko12** [comment]
Thank you for the comment, @rsmml .  But I don't think we should limit one branch per one file. 
After I sent a first pull request and started working on this branch, I noticed I needed to change the booking price. I thought it's ok to resolve the conflict when it happens.

**Comment by sorina-duca** [comment]
So you have to resolve conflicts before we merge, right?  Or should the person merging resolve the conflicts? I was thinking to merge everything in order to to see if there are any bugs in the app before smbd pushes to heroku, but I will wait to discuss. 

I was thinking to have a method for cancelling that works with the following logic - if the booking is not yet approved, cancel will delete the booking altogether - so we won't show cancelled bookings and the owner will no longer have to deal with it. 
If the booking is already approved, tough luck, you cannot cancel anymore (of course in real life you probably get some money back or something, but as yet we are not really doing any payments). But I guess we could also leave it like this and maybe turn the cancelled bookings a grey color, so they look disabled or smth similar.

**Pull request merged**
