### PR TITLE
add datepick to bookings/new page

### PR DESCRIPTION
**Pull request by sorina-duca**
I added the datepicker to the new booking page. 

The logic behind it still needs to be done - add available dates in the boat model etc.

### CODE REVIEW

**Comment by sorina-duca** [comment]
Please don't merge yet, until we decide if we keep the hours.

**Comment by sorina-duca** [comment]
Ready for merge.

**Comment by sorina-duca** [comment]
Please DON'T delete branch if you merge, i want to keep working on this feature when I have time. I think that if I work on this branch and someone deletes it, maybe I will be unable to push the work.

**Comment by sorina-duca** [comment]
Now the form for making a new booking will show as disabled the dates when the boat is already booked. 

Since we don't have a method to approve bookings yet, even unaccepted bookings are disabled. Will fix that when we can approve bookings. 

Please check out and merge.
Screenshot 2020-07-10 at 21 32 38

**Comment by rsmml** [comment]
Wow that looks awesome!! Good job :smile: now you have to teach us what you did haha.

**Pull request merged**
