### PR TITLE
Installing messages

### PR DESCRIPTION
**Pull request by rsmml**
- Chat with Owner:
 I implement a new table of messages and another of conversations that creates a chat-box with the boat owner. In case we need to ask a question... 
- [Here](https://recordit.co/ao4u2a0dB3) you can take a look

 **NOT ready to merge**

- Basically there's a new messages link where you can see all your messages with the people that contact you.
- The user can contact the owner of the boat with a btn on the boat show page.
- I still need to design a  better the chat box, because it look awful  now hahah.

### CODE REVIEW

**Comment by rsmml** [comment]
Messages Chat view updated:
Screen Shot 2020-07-14 at 16 33 05

**Comment by rsmml** [comment]
Not ready to merge. I still have to work with the Authorizations.

**Comment by chihoko12** [comment]
Wow. Well done!

**Comment by sorina-duca** [comment]
Wow, impressive. I can't wait for it to be merged to check it out. Is it now ready?

**Pull request merged**
